In [2]:
import numpy as np
from sklearn import preprocessing

In [19]:
X=np.array([[1.,-1.,2.],
           [2.,0.,0.],
           [0.,1.,-1.],
           [1.,0.,4.]])

In [25]:
X_scaled=preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.41421356,  0.39056673],
       [ 1.41421356,  0.        , -0.65094455],
       [-1.41421356,  1.41421356, -1.1717002 ],
       [ 0.        ,  0.        ,  1.43207802]])

In [22]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [23]:
X_scaled.std(axis=0) 

array([1., 1., 1.])

In [24]:
scaler=preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.41421356,  0.39056673],
       [ 1.41421356,  0.        , -0.65094455],
       [-1.41421356,  1.41421356, -1.1717002 ],
       [ 0.        ,  0.        ,  1.43207802]])

In [32]:
X_test=np.array([[1,1,0],
                [2,1,0]]  )
scaler.transform(X_test)
X_test.mean(axis=0)
X_test.std(axis=0)

array([0.5, 0. , 0. ])