In [1]:
# we just have only one output unit layer
# we don't have any hidden layer
import numpy as np

In [2]:
# taking 'and' gate
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
print(x.shape,y.shape)

(4, 2) (4, 1)


In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
# no hidden layer weights
# weights=np.random.random((2,1))  it ranges from 0 to 1
# we have to make it from -1 to 1 
# for that we can apply this
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights,bias

(array([[0.82288369],
        [0.87294896]]), array([-0.14902979]))

In [6]:
# forward propagation without any hidden layer 
output0=x
output=sig(np.dot(output0,weights)+bias)
output

array([[0.46281136],
       [0.67346946],
       [0.66236557],
       [0.82445149]])

In [7]:
# no.of units in the input layer=2
# no.of units in the hidden layer=2
wh=2*np.random.random((2,2))-1 
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [10]:
# forward propagation with a hidden layer 
output0=x
outputhidden=sig(np.dot(output0,wh)+bh)
output=sig(np.dot(outputhidden,wo)+bo)
output


array([[0.42831839],
       [0.37418935],
       [0.49278157],
       [0.42707206]])