In [1]:
# we just have only one output unit layer
# we don't have any hidden layer
import numpy as np

In [2]:
# taking 'and' gate
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
print(x.shape,y.shape)

(4, 2) (4, 1)


In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [28]:
# no hidden layer weights
# weights=np.random.random((2,1))  it ranges from 0 to 1
# we have to make it from -1 to 1 
# for that we can apply this
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
lr=0.1
weights,bias

(array([[0.46883851],
        [0.2125628 ]]), array([0.29160148]))

In [6]:
# forward propagation without any hidden layer 
for iter in range(1000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)

    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    changes=np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(len(first_two)):
            changes[i][0]+=first_two[j][0]*output0[j][i]
    weights-=lr*changes

    bias_changes=0.0
    for j in range(len(first_two)):
        bias_changes+=first_two[j][0]*1
    bias-=lr*bias_changes
output=sig(np.dot(output0,weights)+bias)
weights,bias,output

(array([[0.92971343],
        [0.26215461]]), array([-1.09534729]), array([[0.25061269],
        [0.30297042],
        [0.45868594],
        [0.52411147]]))

In [29]:
# forward propagation without any hidden layer 
# optimization in code
for iter in range(10000):
    output0=x
    output=sig(np.dot(output0,weights)+bias)

    first_term=output-y
    input_for_last_layer=np.dot(output0,weights)+bias
    second_term=derivativeSig(input_for_last_layer)
    first_two=first_term*second_term
    
    
    changes=np.dot(output0.T,first_two)
    weights-=lr*changes
    bias_changes=np.sum(first_two)
    bias-=lr*bias_changes
output=sig(np.dot(output0,weights)+bias)
weights,bias,output
# output0.T,first_two

(array([[5.47759131],
        [5.47759131]]), array([-8.30908723]), array([[2.46208093e-04],
        [5.56457358e-02],
        [5.56457360e-02],
        [9.33769923e-01]]))